"""Define the SQLAlchemy model and database session for Module 3."""

import os
from datetime import date
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from sqlalchemy import Date, Float, Integer, String, URL, create_engine
from sqlalchemy import func, select
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    sessionmaker,
)


# Find the module_3 directory and load its ignored .env file.
BASE_DIR = Path(__file__).resolve().parent
ENV_FILE = BASE_DIR / ".env"

load_dotenv(ENV_FILE)


# URL.create() builds a valid SQLAlchemy connection URL without manually
# combining the username, password, host, port, and database into a string.
DATABASE_URL = URL.create(
    drivername="postgresql+psycopg",
    username=os.getenv("DB_USER", "karimzaky"),
    password=os.getenv("DB_PASSWORD") or None,
    host=os.getenv("DB_HOST", "localhost"),
    port=int(os.getenv("DB_PORT", "5432")),
    database=os.getenv("DB_NAME", "gradcafe_module3"),
)


# The Engine manages database connections for SQLAlchemy.
engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,
)


# SessionLocal is a factory for SQLAlchemy Session objects.
SessionLocal = sessionmaker(
    bind=engine,
    expire_on_commit=False,
)


class Base(DeclarativeBase):
    """Base class inherited by every SQLAlchemy model."""

    pass


class Applicant(Base):
    """
    Map the existing PostgreSQL applicants table to a Python class.

    Each Applicant object represents one row in the applicants table.
    """

    __tablename__ = "applicants"

    # Primary key generated by PostgreSQL.
    p_id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    # Original GradCafe program and university text.
    program: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,
    )

    # Optional applicant comments.
    comments: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,
    )

    # Date on which the result was added to GradCafe.
    date_added: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
    )

    # Each GradCafe result URL uniquely identifies a record.
    url: Mapped[str] = mapped_column(
        String,
        unique=True,
        nullable=False,
    )

    # Admission result, such as Accepted, Rejected, or Interview.
    status: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,
    )

    # Intended enrollment term, such as Fall 2026.
    term: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,
    )

    # Applicant nationality classification.
    us_or_international: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,
    )

    # Optional academic metrics.
    gpa: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    gre: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    gre_v: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    gre_aw: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    # Degree category, such as PhD, Masters, or MFA.
    degree: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,
    )

    # Program and university names normalized by the Module 2 LLM.
    llm_generated_program: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,
    )

    llm_generated_university: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,
    )

    def __repr__(self):
        """Return a concise developer-friendly representation."""
        return (
            f"Applicant(p_id={self.p_id!r}, "
            f"program={self.program!r}, "
            f"status={self.status!r})"
        )


def test_model_connection():
    """
    Test the ORM mapping by counting Applicant objects.

    This uses SQLAlchemy's select() and func.count(), not raw SQL.
    """
    with SessionLocal() as session:
        applicant_count = session.scalar(
            select(func.count(Applicant.p_id))
        )

    print(f"SQLAlchemy Applicant count: {applicant_count:,}")


# Run the connection test only when models.py is executed directly.
# Importing models.py from another file will not automatically run it.
if __name__ == "__main__":
    test_model_connection()